### ISSUE TITLE
Hank Risk when building with Xcode 14.3

### ISSUE THREAD

**Issue by xmollv** [configcat/swift-sdk#35]
### Describe the bug

Xcode 14.3 started warning about this possible hang risk:

```
Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions.
```

It happens in `ConfigCatClient.getValueSync(for:defaultValue:user:):167`, in the `semaphore.wait()` call.

### To reproduce

Compile the app using Xcode 14.3 and run it.

### Expected behavior

No warnings about possible thread hangs.

### Screenshots

<img width="863" alt="image" src="https://user-images.githubusercontent.com/8229382/229145283-000cae22-69d2-4b95-842b-343692e73503.png">

**Comment by boazFrenkel** [comment]
Any updates on this?

**Comment by z4kn4fein** [comment]
Hi @xmollv and @boazFrenkel, thank you for reporting this! I'm going to fix this warning, and I'll keep you posted here.

**Comment by boazFrenkel** [comment]
@z4kn4fein 
For me it happens on a ConfigCat: class Synced<Value: Equatable>

on the function:
func testAndSet(expect: Value, new: Value) -> Bool {
        lock.wait()
        defer { lock.signal() }
        let challange = self.value == expect
        self.value = challange ? new : self.value
        return challange
    }
    
    and specificaly on the lock.wait()
    
As Apple wrote in the https://developer.apple.com/documentation/xcode/diagnosing-performance-issues-early
 "If you use concurrency primitives, such as dispatch_semaphore_wait and dispatch_group_wait, in your code or invoke APIs that use them, your app is susceptible to priority inversions if there is a mismatch in the quality-of-service (QoS) class of the dispatch queues your app uses."

In my case, I'm calling the class from "QOS_CLASS_USER_INITIATED"
Since I do not have access to ConfiCat, I resolved this issue by handling the QOS from the calling site like this:

let backgroundQueue = DispatchQueue(label: "background_queue",
                                            qos: .background)
        
backgroundQueue.async {[weak self] in
    // Call the class you need here and it will be done on a background QOS
}

**Comment by z4kn4fein** [comment]
Thanks for the addition @boazFrenkel. I'll also refactor that part to get rid of the warning in each part of the project.

**Comment by z4kn4fein** [comment]
@boazFrenkel I just realized that the `Synced` class is not been using `DispatchSemaphore` since `v9.0.0`. Are you using an older version of the SDK? Is it possible for you to upgrade?

**Comment by z4kn4fein** [comment]
@xmollv For context, `getValueSync` and each method on the SDKs API ending with `...Sync` was left on the API for backward compatibility reasons for cases where blocking the calling thread is an intended choice of the user. I don't see any official resolution for how we could continue supporting those synchronous methods without the danger of priority inversion. 

Is there a specific reason for using those methods instead of the `getValue() async` variations?

I would mark those methods obsolete for now because there's no point in keeping them with their dangerous synchronization path.

**Comment by xmollv** [comment]
> @xmollv For context, `getValueSync` and each method on the SDK's API ending with `...Sync` was left on the API for backward compatibility reasons for cases where blocking the calling thread (with `DispatchSemaphore`) is an intended choice of the user. After some investigation, I don't see any official resolution for how we could continue supporting those synchronous methods without the danger of priority inversion.
> 
> Do you have a specific reason for using those methods instead of the `getValue() async` variations?
> 
> I would mark those methods obsolete for now because there's no point in keeping them with their dangerous synchronization path.

@z4kn4fein To be honest, I didn't implement the feature flagging system in my current project, so I'm not entirely sure why that was chosen. But in my opinion, if those methods should not be used, I'd say go ahead and mark them as deprecated so we can see all the warnings popping up the next time that we update the ConfigCat dependency and act on them.

**Comment by z4kn4fein** [comment]
@xmollv I'll do that. Thanks for the feedback!

**Comment by z4kn4fein** [comment]
Each `...Sync()` method has been marked as deprecated. They'll be removed in the next major update.
